# Set up

In [1]:
import pandas as pd

# Input Arguments

In [2]:
DATASET_DP = f'../data/yelp_dataset/sample'

# Load data

In [3]:
# Load reviews
review_df = pd.read_parquet(f"{DATASET_DP}/yelp_academic_dataset_review_sample_1K_biz.parquet")

In [4]:
review_df

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
0,ZKvDG2sBvHVdF5oBNUOpAQ,wSTuiTk-sKNdcFyprzZAjg,B5XSoSG3SfvQGtKEGQ1tSQ,3,1,1,0,This easter instead of going to Lopez Lake we ...,2016-03-30 22:46:33
1,u2vzZaOqJ2feRshaaF1doQ,NDZvyYHTUWWu-kqgQzzDGQ,CLEWowfkj-wKYJlQDqT1aw,5,2,0,1,I go to blow bar to get my brows done by natal...,2016-03-07 00:02:18
2,40thYphUgIfvJq17QCfTwA,QzCEzH3R7Z6erOGLr3t55Q,0pMj5xUAecW9o1P35B0AMw,5,1,0,1,Great staff always helps and always nice. Alwa...,2017-05-26 13:10:24
3,L0jv8c2FbpWSlfNC6bbUEA,bFPdtzu11Oi0f92EAcjqmg,IDtLPgUrqorrpqSLdfMhZQ,5,0,0,0,What a great addition to the Funk Zone! Grab ...,2016-10-13 22:50:47
4,JBWZmBy69VMggxj3eYn17Q,aFa96pz67TwOFu4Weq5Agg,kq5Ghhh14r-eCxlVmlyd8w,5,0,0,0,My boyfriend and I tried this deli for the fir...,2018-08-23 21:39:38
...,...,...,...,...,...,...,...,...,...
50852,KIO40b2aN1GFwCtsCih3tw,ueRPE0CX75ePGMqOFVj6IQ,TLZ3-eDPLhUzfsWO4ad6Ug,5,3,1,3,This place was ABSOLUTELY fantastic. I am not ...,2019-09-25 15:48:16
50853,gIuVPPnEjFO6TYpdKHl-WA,TtuLyYy4Gf41XA2JUQgY8A,TGfPJHImEq6AQL9a1laxlg,1,2,0,0,After tonight's experience I will not be back ...,2017-11-04 01:20:55
50854,rlDUP5rfoJYoab0Raj71VQ,lhTCrBZO3BF9beho8vPXAw,SZU9c8V2GuREDN5KgyHFJw,5,1,0,1,Absolutely love this place! From the service t...,2018-11-27 22:22:09
50855,gfGXPkDcIv-Zqv69VCSYsg,vjLQ8F8opdDXGyXISRnuYQ,gl9APAes1BYYt_8UsDVsPg,5,1,0,1,If you enjoy no frills old school diners as mu...,2022-01-18 16:44:12
50856,rT1xsfmuaQWCcgKcA-NJXw,DgmvcnJT9G2O0FdxtpEO-w,TJe1ZGe-X0-GjOQd00kKxA,3,3,0,0,"I heard about this place from a coworker, who ...",2019-09-15 16:36:26

# Load business

In [7]:
# Load businesses
business_df = pd.read_parquet(f"{DATASET_DP}/yelp_academic_dataset_business_sample_1K_biz.parquet")
business_df

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,CA,93101,34.426679,-119.711197,5.0,7,0,"{'AcceptsInsurance': None, 'Alcohol': None, 'A...","Doctors, Traditional Chinese Medicine, Naturop...",None
1,mpf3x-BjTdTEA3yCZrAYPw,The UPS Store,87 Grasso Plaza Shopping Center,Affton,MO,63123,38.551126,-90.335695,3.0,15,1,"{'AcceptsInsurance': None, 'Alcohol': None, 'A...","Shipping Centers, Local Services, Notaries, Ma...","{'Friday': '8:0-18:30', 'Monday': '0:0-0:0', '..."
2,tUFrWirKiKi_TAnsVWINQQ,Target,5255 E Broadway Blvd,Tucson,AZ,85711,32.223236,-110.880452,3.5,22,0,"{'AcceptsInsurance': None, 'Alcohol': None, 'A...","Department Stores, Shopping, Fashion, Home & G...","{'Friday': '8:0-23:0', 'Monday': '8:0-22:0', '..."
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,1,"{'AcceptsInsurance': None, 'Alcohol': 'u'none'...","Restaurants, Food, Bubble Tea, Coffee & Tea, B...","{'Friday': '7:0-21:0', 'Monday': '7:0-20:0', '..."
4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,101 Walnut St,Green Lane,PA,18054,40.338183,-75.471659,4.5,13,1,"{'AcceptsInsurance': None, 'Alcohol': None, 'A...","Brewpubs, Breweries, Food","{'Friday': '12:0-22:0', 'Monday': None, 'Satur..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,iNMdSi5bmvGSGeRQiUW4dw,Wendy's,3535 E. Irvington Road,Tucson,AZ,85714,32.163740,-110.916722,2.5,14,1,"{'AcceptsInsurance': None, 'Alcohol': 'u'none'...","Fast Food, Burgers, Restaurants","{'Friday': '10:0-0:0', 'Monday': '10:0-23:0', ..."
996,0QmgzzPVNHeNL76B8rwTKA,Beneficial Bank,1600 Chestnut St,Philadelphia,PA,19103,39.951154,-75.167335,2.5,5,0,None,"Banks & Credit Unions, Financial Services","{'Friday': '8:30-18:0', 'Monday': '8:30-17:0',..."
997,ByDCN9n5mwHP9LQqUx-1pw,Largo Police Department,201 Highland Ave,Largo,FL,33770,27.920194,-82.776363,2.5,7,1,None,"Public Services & Government, Police Departments",None
998,TwIouh_gbW9TCSK3PhuPrg,T J Maxx,545 Cool Springs Blvd,Franklin,TN,37067,35.948462,-86.823777,3.0,28,1,"{'AcceptsInsurance': None, 'Alcohol': None, 'A...","Fashion, Shopping, Department Stores",None
999,sDOxVq8gQBpHFYtoxwoLWw,Plume Salon,111 E Girard Ave,Philadelphia,PA,19125,39.969190,-75.134038,4.5,138,1,"{'AcceptsInsurance': None, 'Alcohol': None, 'A...","Waxing, Beauty & Spas, Eyelash Service, Used, ...","{'Friday': '10:0-20:0', 'Monday': '12:0-20:0',..."

# Join review and business

In [13]:
denom_df = (
    pd.merge(
        # TODO: Fix duplicated columns
        review_df.rename(columns={'stars': 'review_stars'}),
        # business_df.rename(columns={'stars': 'business_avg_stars'}),
        business_df.add_prefix("biz_").rename(columns={'biz_business_id': 'business_id'}),
        how='left',
        on='business_id',
        validate='m:1'
    )
)

denom_df

,review_id,user_id,business_id,review_stars,useful,funny,cool,text,date,biz_name,...,biz_state,biz_postal_code,biz_latitude,biz_longitude,biz_stars,biz_review_count,biz_is_open,biz_attributes,biz_categories,biz_hours
0,ZKvDG2sBvHVdF5oBNUOpAQ,wSTuiTk-sKNdcFyprzZAjg,B5XSoSG3SfvQGtKEGQ1tSQ,3,1,1,0,This easter instead of going to Lopez Lake we ...,2016-03-30 22:46:33,Los Padres National Forest,...,CA,93105,34.597239,-119.510772,4.5,13,1,"{'AcceptsInsurance': None, 'Alcohol': None, 'A...","Parks, Active Life",None
1,u2vzZaOqJ2feRshaaF1doQ,NDZvyYHTUWWu-kqgQzzDGQ,CLEWowfkj-wKYJlQDqT1aw,5,2,0,1,I go to blow bar to get my brows done by natal...,2016-03-07 00:02:18,Blow Bar Express Styling Salon,...,FL,33609,27.941975,-82.505307,4.0,55,1,"{'AcceptsInsurance': None, 'Alcohol': None, 'A...","Makeup Artists, Blow Dry/Out Services, Beauty ...","{'Friday': '9:0-19:0', 'Monday': '0:0-0:0', 'S..."
2,40thYphUgIfvJq17QCfTwA,QzCEzH3R7Z6erOGLr3t55Q,0pMj5xUAecW9o1P35B0AMw,5,1,0,1,Great staff always helps and always nice. Alwa...,2017-05-26 13:10:24,Wawa,...,PA,19403,40.141292,-75.389286,3.5,8,1,"{'AcceptsInsurance': None, 'Alcohol': None, 'A...","Food, Coffee & Tea, Gas Stations, Restaurants,...","{'Friday': '0:0-0:0', 'Monday': '0:0-0:0', 'Sa..."
3,L0jv8c2FbpWSlfNC6bbUEA,bFPdtzu11Oi0f92EAcjqmg,IDtLPgUrqorrpqSLdfMhZQ,5,0,0,0,What a great addition to the Funk Zone! Grab ...,2016-10-13 22:50:47,Helena Avenue Bakery,...,CA,93101,34.414445,-119.690672,4.0,389,1,"{'AcceptsInsurance': None, 'Alcohol': 'u'none'...","Food, Restaurants, Salad, Coffee & Tea, Breakf...","{'Friday': '8:0-14:0', 'Monday': '0:0-0:0', 'S..."
4,JBWZmBy69VMggxj3eYn17Q,aFa96pz67TwOFu4Weq5Agg,kq5Ghhh14r-eCxlVmlyd8w,5,0,0,0,My boyfriend and I tried this deli for the fir...,2018-08-23 21:39:38,The Coventry Deli,...,PA,19103,39.953291,-75.173645,4.0,65,1,"{'AcceptsInsurance': None, 'Alcohol': 'u'none'...","Restaurants, Delis, Salad, Sandwiches","{'Friday': '6:0-15:0', 'Monday': '6:0-15:0', '..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50852,KIO40b2aN1GFwCtsCih3tw,ueRPE0CX75ePGMqOFVj6IQ,TLZ3-eDPLhUzfsWO4ad6Ug,5,3,1,3,This place was ABSOLUTELY fantastic. I am not ...,2019-09-25 15:48:16,Mahony's Po-Boys & Seafood,...,LA,70112,29.955415,-90.070062,4.0,382,1,"{'AcceptsInsurance': None, 'Alcohol': ''full_b...","Restaurants, Seafood, Cajun/Creole","{'Friday': '12:0-20:0', 'Monday': '0:0-0:0', '..."
50853,gIuVPPnEjFO6TYpdKHl-WA,TtuLyYy4Gf41XA2JUQgY8A,TGfPJHImEq6AQL9a1laxlg,1,2,0,0,After tonight's experience I will not be back ...,2017-11-04 01:20:55,Chick-fil-A,...,PA,19114,40.081780,-75.026791,4.0,80,1,"{'AcceptsInsurance': None, 'Alcohol': 'u'none'...","Event Planning & Services, American (Tradition...","{'Friday': '6:30-22:0', 'Monday': '0:0-0:0', '..."
50854,rlDUP5rfoJYoab0Raj71VQ,lhTCrBZO3BF9beho8vPXAw,SZU9c8V2GuREDN5KgyHFJw,5,1,0,1,Absolutely love this place! From the service t...,2018-11-27 22:22:09,Santa Barbara Shellfish Company,...,CA,93101,34.408715,-119.685019,4.0,2404,1,"{'AcceptsInsurance': None, 'Alcohol': ''beer_a...","Live/Raw Food, Restaurants, Seafood, Beer Bar,...","{'Friday': '11:0-21:0', 'Monday': '0:0-0:0', '..."
50855,gfGXPkDcIv-Zqv69VCSYsg,vjLQ8F8opdDXGyXISRnuYQ,gl9APAes1BYYt_8UsDVsPg,5,1,0,1,If you enjoy no frills old school diners as mu...,2022-01-18 16:44:12,Ted's Luncheonette,...,FL,33770,27.927861,-82.796198,4.0,37,1,"{'AcceptsInsurance': None, 'Alcohol': 'u'none'...","Breakfast & Brunch, Restaurants","{'Friday': '6:30-14:30', 'Monday': '6:30-14:30..."
50856,rT1xsfmuaQWCcgKcA-NJXw,DgmvcnJT9G2O0FdxtpEO-w,TJe1ZGe-X0-GjOQd00kKxA,3,3,0,0,"I heard about this place from a coworker, who ...",2019-09-15 16:36:26,Brixx Craft House,...,ID,83714,43.671633,-116.283591,4.0,115,1,"{'AcceptsInsurance': None, 'Alcohol': 'u'full_...","American (Traditional), Pubs, Sports Bars, Nig...","{'Friday': '11:30-22:0', 'Monday': '0:0-0:0', ..."

In [14]:
denom_df.describe(include='all').T

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
review_id,50857,50857,rT1xsfmuaQWCcgKcA-NJXw,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
user_id,50857,45077,_BcWyKQL16ndpBdggh2kNA,30,NaN,NaN,NaN,NaN,NaN,NaN,NaN
business_id,50857,1000,SZU9c8V2GuREDN5KgyHFJw,2444,NaN,NaN,NaN,NaN,NaN,NaN,NaN
review_stars,50857.0,NaN,NaN,NaN,3.759541,1.0,3.0,4.0,5.0,5.0,1.461076
useful,50857.0,NaN,NaN,NaN,1.144916,0.0,0.0,0.0,1.0,149.0,2.743448
funny,50857.0,NaN,NaN,NaN,0.30574,0.0,0.0,0.0,0.0,133.0,1.382071
cool,50857.0,NaN,NaN,NaN,0.460232,0.0,0.0,0.0,0.0,145.0,1.836822
text,50857,50786,We had another great lunch at Mr B's on 3/12/1...,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
date,50857,NaN,NaN,NaN,2017-01-05 10:52:31.859488512,2005-03-12 03:47:06,2015-01-10 22:07:15,2017-06-14 17:42:26,2019-05-09 02:42:58,2022-01-19 19:45:32,NaN
biz_name,50857,960,Santa Barbara Shellfish Company,2444,NaN,NaN,NaN,NaN,NaN,NaN,NaN
biz_address,50857,960,230 Stearns Wharf,2444,NaN,NaN,NaN,NaN,NaN,NaN,NaN
biz_city,50857,226,Philadelphia,7118,NaN,NaN,NaN,NaN,NaN,NaN,NaN
biz_state,50857,14,PA,11160,NaN,NaN,NaN,NaN,NaN,NaN,NaN
biz_postal_code,50857,445,93101,3665,NaN,NaN,NaN,NaN,NaN,NaN,NaN
biz_latitude,50857.0,NaN,NaN,NaN,36.16637,27.5843,32.219336,36.211592,39.941877,53.63016,5.011062
biz_longitude,50857.0,NaN,NaN,NaN,-91.389908,-119.886915,-90.515066,-86.775973,-75.662182,-74.753212,15.662941
biz_stars,50857.0,NaN,NaN,NaN,3.759541,1.0,3.5,4.0,4.0,5.0,0.731591
biz_review_count,50857.0,NaN,NaN,NaN,419.264939,5.0,51.0,161.0,402.0,2404.0,653.009471
biz_is_open,50857.0,NaN,NaN,NaN,0.837702,0.0,1.0,1.0,1.0,1.0,0.368728
biz_attributes,49473,676,"{'AcceptsInsurance': None, 'Alcohol': ''beer_a...",2444,NaN,NaN,NaN,NaN,NaN,NaN,NaN
biz_categories,50857,887,"Live/Raw Food, Restaurants, Seafood, Beer Bar,...",2444,NaN,NaN,NaN,NaN,NaN,NaN,NaN
biz_hours,48268,709,"{'Friday': '0:0-0:0', 'Monday': '0:0-0:0', 'Sa...",3067,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Persist data

In [15]:
DENOM_REVIEW_FP = f'{DATASET_DP}/denom_review.parquet'
denom_df.to_parquet(DENOM_REVIEW_FP, index=False)